### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by heron2014** [ffs-org/feministfilmsocial#9]
- [ ] hook up form
- [ ] css success message
- [ ] welcome email
- [ ] fix svg jumps (vh)
- [ ] add to footer email
- [ ] font
- [ ] favicon
- [ ] play chess game!!!
